modal component作成
moto2318/my_project pull request #1
Opened 2024-02-09 09:21 UTC by moto2318

テスト投稿

2024-02-09 09:25 UTC, kapureka6174 requested changes
@moto2318 
hello worldに変更しましょう！

2024-02-09 09:28 UTC, kapureka6174 approved these changes
@moto2318 
LFTM!

2024-02-13 01:03 UTC, moto2318 commented
@kapureka6174 
modalの実装を行いましたので、確認お願いします。

2024-02-13 02:54 UTC, kapureka6174 requested changes
@moto2318 
レビューしましたので、修正お願いします。

2024-02-13 02:54 UTC, kapureka6174 commented on public/js/build/top/index.js
@moto2318 
buildされるファイルは.gitignoreに追加して、git管理から外していただいて大丈夫です。

2024-02-13 02:54 UTC, kapureka6174 commented on public/js/build/top/index.js.gz
@moto2318
buildされるファイルは.gitignoreに追加して、git管理から外していただいて大丈夫です。

2024-02-13 02:54 UTC, kapureka6174 commented on resources/views/top/index.blade.php
@moto2318 
htmlの構造自体がおかしいので修正お願いします。
また、今回のタスクはvueコンポーネントとしてmodalを実装するというものです。

現状、vueを一切使用していないので、vueのコンポーネントとして実装してください。

2024-02-13 04:13 UTC, moto2318 commented
@kapureka6174 
使用言語をvueに直してコードを修正したしました。確認よろしくお願いします。

**modalの使用言語の変更（htmlからvueに）**
/Users/apple/sample_web_template/www/sample_web
modalの表示方法を変更しました。

2024-02-13 05:10 UTC, kapureka6174 requested changes
@moto2318 
お疲れ様です。
レビューしました。

2024-02-13 05:10 UTC, kapureka6174 commented on resources/views/top/index.blade.php
@moto2318 
お疲れ様です。

レビューしました。以下、修正お願いします。

1. このファイルのhtmlの構造がおかしいのは修正できていません。まず、htmlの構造、閉じタグなどがどこに対応しているのかなど、確認し正しく修正してください。
2. コンポーネントはSFCとして作成し、sample-componentと同じような形で読み込むようにしてください。
3. jsでdisplayを直接操作せずとも、vueのビルドインのディレクティブが用意されているはずです。そちらを使用するように修正してください。

2024-02-14 03:56 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。

modalの内容を修正いたしました、確認お願いします。


**修正コード**
Modal.vue  (resouces/js/top/)
index.js  (resouces/js/top/)
index.blade.php.   (resouces/views/top/)

**修正内容**
phpとjsのコードを極力省き、Modal.vueに表示する内容を載せております。

2024-02-14 04:56 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。

modalの内容を修正いたしました、確認お願いします。


**修正コード**
Modal.vue  (resouces/js/top/)
index.js  (resouces/js/top/)
index.blade.php.   (resouces/views/top/)

**修正内容**
phpとjsのコードを極力省き、Modal.vueに表示する内容を載せております。
またvue内の変数をshow → isShowに変更、レイアウトも画面中央に来るように変更しております。

2024-02-14 05:35 UTC, kapureka6174 requested changes
@moto2318 
お疲れ様です。
動作部分については大丈夫です。

ただ、一部必要のない記述がありますのでそちらの修正をお願いします。

チーム開発する上では、必要のないコードがあると理解の妨げになってしまったり、肥大化するとパフォーマンスの低下につながる場合があります。一つ一つの記述が必要かどうか、どんな意味があるのか考えてな過不足のない実装を心がけましょう。

2024-02-14 05:35 UTC, kapureka6174 commented on resources/js/top/Modal.vue
> +        <div id="app">
@moto2318 
このidがある目的はなんでしょうか？
必要でなければ削除しましょう。

2024-02-14 05:35 UTC, kapureka6174 commented on resources/js/top/index.js
> +app.mount('#app');
@moto2318 
appという変数を用意する理由は何でしょうか？（変数を使うということは、その分のメモリを確保するということでもあるので）
こちらは`createApp`関数のみを使う形で書き直しましょう。

2024-02-14 05:35 UTC, kapureka6174 commented on resources/views/top/index.blade.php
> +        <div class="justifiy-content-center" id="app" >
@moto2318 
このクラスを指定している理由は何でしょうか？
必要なければ削除してください。

2024-02-14 05:44 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。
必要のないクラスでしたので修正いたしました。


**修正箇所**
resouces/views/top/index.blade.phpの
<div class="justifiy-content-center" id="app" >
↓
<div id="app" >　　　に修正いたしました。

2024-02-14 06:10 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。
コードの無駄を修正いたしました。お時間がある時に確認お願いいたします。

2024-02-14 06:21 UTC, kapureka6174 requested changes
@moto2318 
レビューしましたので、修正お願いします。

過不足ない、可読性の高いコードを目指しましょう。

2024-02-14 06:21 UTC, kapureka6174 commented on resources/js/top/Modal.vue
> +        console.log('click');
指摘しませんでしたが、こちらは実際にコードが動くのに必要でしょうか？
また、今回は特に言いませんでしたが、インデントについても適切に設定しましょう。
階層構造が見にくいです。できるだけコードを読む人の認知負荷を下げるよう心がけましょう。

2024-02-14 06:21 UTC, kapureka6174 commented on resources/views/top/index.blade.php
> +        <div id="app" >
エラーにはならないと思いますが、閉じたタグの後ろの空白は必要ないので削除しましょう。

2024-02-14 06:21 UTC, kapureka6174 commented on resources/views/top/index.blade.php
> +        {{-- <script src="https://unpkg.com/vue@3"></script> --}}
必要ないものは削除しましょう。

2024-02-14 06:26 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。
コードの修正いたしました。お時間のある時に確認よろしくお願いします。

2024-02-14 07:00 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。
ご指摘いただいた内容の修正をいたしました。お時間のある時に確認よろしくお願いします。

2024-02-14 07:14 UTC, kapureka6174 requested changes
@moto2318 
レビューしましたので、修正お願いします。

2024-02-14 07:14 UTC, kapureka6174 commented on resources/js/top/index.js
> +    .mount('#app')
@moto2318 
先ほどのレビューにもなりますが、appという変数に代入するのは何故でしょうか？
必要のない代入は避けましょう。

一応、createAppの引数としてcomponentsを渡して宣言することも可能なので、以下のように書くこともできます。
```js
createApp({
  components: {
    Modal
  }
}).mount("#app")
```

2024-02-14 08:27 UTC, moto2318 commented
@kapureka6174 
お疲れ様です。コードの表記を修正いたしました。
**変更点**
resouces/js/top/index.js の表記を上記の内容に変更

2024-02-14 08:30 UTC, kapureka6174 approved these changes
@moto2318 
お疲れ様です。
LGTMです！

2024-02-14 08:34 UTC, merged